name: PSScriptAnalyzer

on:
  push:
    paths:
      - "**.ps1"
      - "**.psm1"
      - "**.psd1"
  pull_request:
    paths:
      - "**.ps1"
      - "**.psm1"
      - "**.psd1"
  workflow_dispatch:

jobs:
  lint:
    name: PSScriptAnalyzer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v4.2.2
      - name: Run PSScriptAnalyzer
        shell: pwsh
        run: |
          $psFiles = Get-ChildItem -Recurse -Include *.ps1, *.psm1, *.psd1 -Exclude node_modules, bin, obj
          if ($psFiles) {
            Install-Module -Name PSScriptAnalyzer -Force -Scope CurrentUser
            $results = Invoke-ScriptAnalyzer -Path $psFiles.FullName -Recurse
            $errors = $results | Where-Object { $_.Severity -eq 'Error' }
            if ($errors) {
              $errors | Format-Table
              exit 1
            }
          } else {
            Write-Host "No PowerShell files found to analyze."
          }
